### PR TITLE
Fix the default configuration schema for the umbrella DI extension

### LINKED ISSUE #22: Missing default configuration
The default configuration is missing in the latest version `0.5.0`. 

**Error log**:
```
   E_NOTICE: Trying to get property 'generators' of non-object
   
   in src/DI/AdvancedCacheConsoleExtension.php(47) 
   in src/DI/ConsoleBridgesExtension.php(59) Contributte\Console\Extra\DI\AdvancedCacheConsoleExtension->loadConfiguration()
   in src/DI/Compiler.php(229) Contributte\Console\Extra\DI\ConsoleBridgesExtension->loadConfiguration()
   in src/DI/Compiler.php(204) Nette\DI\Compiler->processExtensions()
   in src/DI/ContainerLoader.php(119) Nette\DI\Compiler->compile()
   in src/DI/ContainerLoader.php(79) Nette\DI\ContainerLoader->generate()
   in src/DI/ContainerLoader.php(44) Nette\DI\ContainerLoader->loadFile()
   in src/Bootstrap/Configurator.php(242) Nette\DI\ContainerLoader->load()
   in src/Bootstrap/Configurator.php(221) Nette\Configurator->loadContainer()
   in iqrf-gateway-webapp/tests/bootstrap.php(41) Nette\Configurator->createContainer()
   in ServiceModule/Models/UnknownManagerTest.php(18) require()
```

**Used configuration:** https://gitlab.iqrf.org/open-source/iqrf-gateway-webapp/blob/f5a0f0d16237d40e3dc925331d287a4f93178c70/app/config/console.neon)

### PR DESCRIPTION
**Pull request by Roman3349**
Fixes #22.

Signed-off-by: Roman Ondráček <ondracek.roman@centrum.cz>

### CODE REVIEW

**Comment by f3l1x** [comment]
Thanks @Roman3349. Can you please add extra test for it? To know that everything works just fine.

**Comment by f3l1x** [comment]
ping @Roman3349

**Comment by Roman3349** [comment]
@f3l1x This week I'll try add tests.

File: src/DI/CacheConsoleExtension.php [hunk 1]
```diff
@@ -33,12 +32,12 @@ public function loadConfiguration(): void
 		$config = $this->config;
 
 		// Default values cannot be in schema, arrays are merged by keys
-		if ($config->purge === []) {
-			$config->purge = Helpers::expand(['%tempDir%/cache'], $builder->parameters);
+		if (!isset($config['purge']) || ($config['purge'] === [])) {
+			$config['purge'] = Helpers::expand(['%tempDir%/cache'], $builder->parameters);
```
Comment (mabar) [inline src/DI/CacheConsoleExtension.php]: Why did you change stdClass to array?

Comment (Roman3349) [reply src/DI/CacheConsoleExtension.php]: I have changed `stdClass` to `array` because the default configuration (when extensions are only registered) is [an empty array](https://github.com/nette/di/blob/master/src/DI/CompilerExtension.php#L29). Another option is explicitly use `stdClass` as default value in `ConsoleBridgesExtension::getConfigSchema`.

**Comment by f3l1x** [comment]
Well done. @Roman3349

**Comment by f3l1x** [comment]
Thanks.

**Comment by f3l1x** [comment]
@mabar Bump please new version 0.5.1 version.
